[build]
command = "npm run build"

[build.environment]
NODE_VERSION = "20"

[site]
bucket = "./out"

[env.production]
name = "DoveText"

# This is the key configuration for Pages
[pages_build_output_dir]
directory = "out"
