# Build configuration
name = "dovetext"

# Output directory for Pages
pages_build_output_dir = "out"

# Build command and Node.js version
[build]
command = "npm run build"

# Environment variables for build
[build.environment]
NODE_VERSION = "20"